# Generated by Django 4.1.5 on 2023-01-28 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='groups',
        ),
        migrations.AddField(
            model_name='jobgroup',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sch.team'),
            preserve_default=False,
        ),
    ]
