# Generated by Django 4.1.5 on 2023-01-28 07:25

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0002_remove_team_groups_jobgroup_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sch.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='weekdays',
            field=multiselectfield.db.fields.MultiSelectField(max_length=28, verbose_name=(('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'))),
        ),
    ]
