# Generated by Django 4.1.5 on 2023-01-28 07:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0004_employee_fte_alter_shift_weekdays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='shift',
        ),
        migrations.AddField(
            model_name='employee',
            name='shifts_available',
            field=models.ManyToManyField(related_name='shifts_available', to='sch.shift'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shifts_trained',
            field=models.ManyToManyField(related_name='shifts_trained', to='sch.shift'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='weekdays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=[0, 1, 2, 3, 4, 5, 6], max_length=14),
        ),
    ]
